markdown: kramdown
highlight: pygments
timezone: Australia/Melbourne
exclude: [Rakefile.rb, README.md, CNAME, assets, config, learning, inspiration]
excerpt_separator: ""
relative_permalinks: false
permalink: /:categories/:year-:month-:day/:title.html